### ISSUE TITLE
Using run.py directly

### ISSUE THREAD

**Issue by CrocutaLupus** [mikeyEcology/MLWIC2#9]
Hi,
First, thank you very much for the MLWIC2 it is very interesting.

I am new to python but I was hoping to use the run.py script and to try it on the MLWIC_examples-master'images with the pre-trained model. 

It seems like I am not able to reach the actual pre-trained model. I am having the following error message:
self.pretrained_loader.restore(sess, ckpt.model_checkpoint_path)
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

I have tried to indicate to the run function:
--log_dir ...\Desktop\MLWIC2_helper_files\MLWIC2_helper_files\species_model

Info: I am using Windows, python 3.7.7, and have installed everything as requested for the R package. 

Would you have any idea what I am doing wrong?

Thank you very much in advance for your help.

Best wishes

**Comment by mikeyEcology** [comment]
Hi @CrocutaLupus , something funny happened to this issue so that I can't see what you posted in your issue, but if you want to run directly in the terminal with run.py, you can set `print_cmd=TRUE` and it will give you the command that should be copied an pasted into the terminal. But before pasting, be sure to navigate to the MLWIC2_helper_files directory so that this is your working directory.

**Comment by CrocutaLupus** [comment]
Hi,

Thank you very much for your email and quick reaction.
Yes, something went wrong when I opened the issue. (Can you remove it? It's
solved)
I managed to run the tun.py. but print_cmd=TRUE will be useful thank you.

All the best
